# Generated by Django 2.0.13 on 2019-08-28 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(db_index=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeTrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=9, unique=True)),
                ('sell_amount', models.DecimalField(db_index=True, decimal_places=2, max_digits=18)),
                ('buy_amount', models.DecimalField(db_index=True, decimal_places=2, max_digits=18)),
                ('rate', models.DecimalField(db_index=True, decimal_places=4, max_digits=18)),
                ('date_booked', models.DateField(verbose_name='Date booked')),
                ('buy_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_buy', to='exchange_trades.Currency')),
                ('sell_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_sell', to='exchange_trades.Currency')),
            ],
        ),
    ]
